### ISSUE TITLE
Rename this repository?

### ISSUE THREAD

**Issue by sgalal** [gaozhiyan/nt_input#2]
Hi! Thanks for this project. I would like to include this repository in the [rime schema list](https://github.com/sgalal/awesome-rime). Would you please change the name of this repository to `rime-*`, which complies the rime naming convention?

**Comment by gaozhiyan** [comment]
> Hi! Thanks for this project. I would like to include this repository in the [rime schema list](https://github.com/sgalal/awesome-rime). Would you please change the name of this repository to `rime-*`, which complies the rime naming convention?

changed it. Apologies for not noticing your comment. Keep up the excellent work!

**Comment by sgalal** [comment]
Thanks!
